from time import sleep
from random import randint
game = True
print("Type \"start()\" to start!")
print("open a super pack!")
money = 10
def start():
    inventory = []
    from time import sleep
    game = True
    money = 10
    while game:
        if money >= 1000:
            print("You have become rich by collecting cards! You convert your money into 5 moneys.")
            print("Let's go gamble!")
            exit()
        dostuff = input("What would you like to do? Open a pack (pack) or sell (sell) " + str(money) + " money is your current balance. ")
        if dostuff == "pack":
            wutpack = input("Would you like to open a free pack - free, super pack - $10, rare pack - $35, gamble pack - $50, ultra pack - $100, or a Las Vegas pack - $250. ")
            if wutpack == "free pack":
                if money >= 10:
                    print("you no broke")
                else:
                    print("you get 1 free common")
                    inventory.append("common")
            if wutpack == "super pack":
                if money < 10:
                    print("you broke")
                if money >= 10:    
                    print(" -----------")
                    print(" |         |")
                    print(" |         |")
                    print(" | super   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("           /")
                    print(" ---------/  ")
                    print(" |         |")
                    print(" |         |")
                    print(" | super   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("         /--")
                    print(" -------/   ")
                    print(" |         |")
                    print(" |         |")
                    print(" | super   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("       /----")
                    print(" -----/     ")
                    print(" |         |")
                    print(" |         |")
                    print(" | super   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("     /------")
                    print(" ---/       ")
                    print(" |         |")
                    print(" |         |")
                    print(" | super   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("  /---------")
                    print(" /          ")
                    print(" |         |")
                    print(" |         |")
                    print(" | super   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print(" -----------")
                    print("")
                    print(" |         |")
                    print(" |         |")
                    print(" | super   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    money -= 10
                    card1 = randint(1,815)
                    card2 = randint(1,815)
                    card3 = randint(1,815)
                    pack = [card1, card2, card3]
                    pack.sort()
                    for x in pack:
                        if x <= 400:
                            inventory.append("common")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("common!")
                        if x <= 600 and x > 400:
                            inventory.append("uncommon")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("uncommon!")
                        if x <= 700 and x > 600:
                            inventory.append("rare")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("rare!")
                        if x <= 750 and x > 700:
                            inventory.append("unusual")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("unusual!")
                        if x <= 780 and x > 750:
                            inventory.append("epic")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("epic!")
                        if x <= 800 and x > 780:
                            inventory.append("legendary")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("legendary!")
                        if x <= 810 and x > 800:
                            inventory.append("mythic")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("mythic!")
                        if x <= 815 and x > 810:
                            inventory.append("exotic")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("exotic!")
                    sleep(3)
            if wutpack == "rare pack":
                if money < 35:
                    print("you broke")
                if money >= 35:
                    from time import sleep
                    print(" -----------")
                    print(" |         |")
                    print(" |         |")
                    print(" | rare    |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("           /")
                    print(" ---------/  ")
                    print(" |         |")
                    print(" |         |")
                    print(" | rare    |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("         /--")
                    print(" -------/   ")
                    print(" |         |")
                    print(" |         |")
                    print(" | rare    |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("       /----")
                    print(" -----/     ")
                    print(" |         |")
                    print(" |         |")
                    print(" | rare    |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("     /------")
                    print(" ---/       ")
                    print(" |         |")
                    print(" |         |")
                    print(" | rare    |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("  /---------")
                    print(" /          ")
                    print(" |         |")
                    print(" |         |")
                    print(" | rare    |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print(" -----------")
                    print("")
                    print(" |         |")
                    print(" |         |")
                    print(" | rare    |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    money -= 35
                    card1 = randint(1,326)
                    card2 = randint(1,326)
                    card3 = randint(1,326)
                    card4 = randint(1,326)
                    pack = [card1, card2, card3, card4]
                    pack.sort()
                    for x in pack:
                        if x <= 50:
                            inventory.append("common")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("common!")
                        if x <= 125 and x > 50:
                            inventory.append("uncommon")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("uncommon!")
                        if x <= 300 and x > 125:
                            inventory.append("rare")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("rare!")
                        if x <= 325 and x > 300:
                            inventory.append("unusual")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("unusual!")
                        if x <= 326 and x > 325:
                            inventory.append("exotic")
                            inventory.append("exotic")
                            inventory.append("exotic")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("triple exotic!!!!!!!!!")
            if wutpack == "gamble pack":
                if money < 50:
                    print("you broke")
                if money >= 50:
                    from time import sleep
                    print(" -----------")
                    print(" |         |")
                    print(" |         |")
                    print(" | gamble  |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("           /")
                    print(" ---------/  ")
                    print(" |         |")
                    print(" |         |")
                    print(" | gamble  |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("         /--")
                    print(" -------/   ")
                    print(" |         |")
                    print(" |         |")
                    print(" | gamble  |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("       /----")
                    print(" -----/     ")
                    print(" |         |")
                    print(" |         |")
                    print(" | gamble  |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("     /------")
                    print(" ---/       ")
                    print(" |         |")
                    print(" |         |")
                    print(" | gamble  |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("  /---------")
                    print(" /          ")
                    print(" |         |")
                    print(" |         |")
                    print(" | gamble  |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print(" -----------")
                    print("")
                    print(" |         |")
                    print(" |         |")
                    print(" | gamble  |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    money -= 50
                    card1 = randint(1,101)
                    pack = [card1]
                    pack.sort()
                    for x in pack:
                        if x <= 50:
                            inventory.append("common")
                            inventory.append("uncommon")
                            inventory.append("common")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("2x common and 1x uncommon!")
                        if x <= 90 and x > 50:
                            inventory.append("exotic")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("uncommon!")
                        if x <= 100 and x > 90:
                            inventory.append("exotic")
                            inventory.append("mythic")
                            inventory.append("mythic")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("1x exotic and 2x mythic!")
                        if x <= 101 and x > 100:
                            inventory.append("legendary")
                            inventory.append("legendary")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("double legendary!!")
            if wutpack == "ultra pack":
                if money < 100:
                    print("you broke u need 1 hundo")
                if money >= 100:    
                    print(" -----------")
                    print(" |         |")
                    print(" |         |")
                    print(" | ultra   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("           /")
                    print(" ---------/  ")
                    print(" |         |")
                    print(" |         |")
                    print(" | ultra   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("         /--")
                    print(" -------/   ")
                    print(" |         |")
                    print(" |         |")
                    print(" | ultra   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("       /----")
                    print(" -----/     ")
                    print(" |         |")
                    print(" |         |")
                    print(" | ultra   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("     /------")
                    print(" ---/       ")
                    print(" |         |")
                    print(" |         |")
                    print(" | ultra   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("  /---------")
                    print(" /          ")
                    print(" |         |")
                    print(" |         |")
                    print(" | ultra   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print(" -----------")
                    print("")
                    print(" |         |")
                    print(" |         |")
                    print(" | ultra   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    money -= 100
                    card1 = randint(1,1000)
                    card2 = randint(1,1000)
                    card3 = randint(1,1000)
                    card4 = randint(1,1000)
                    card5 = randint(1,1001)
                    pack = [card1, card2, card3, card4, card5]
                    pack.sort()
                    for x in pack:
                        if x <= 200:
                            inventory.append("uncommon")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("uncommon!")
                        if x <= 600 and x > 200:
                            inventory.append("legendary")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("legendary!")
                        if x <= 900 and x > 600:
                            inventory.append("mythic")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("mythic!")
                        if x <= 1000 and x > 900:
                            inventory.append("exotic")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("exotic!")
                        if x <= 1001 and x > 1000:
                            inventory.append("mystery")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("mystery!")

                    sleep(3)
            if wutpack == "Las Vegas pack" or wutpack == "las vegas pack":
                if money < 250:
                    print("you broke")
                if money >= 100:    
                    print(" -----------")
                    print(" |         |")
                    print(" |         |")
                    print(" | Vegas   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("           /")
                    print(" ---------/  ")
                    print(" |         |")
                    print(" |         |")
                    print(" | Vegas   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("         /--")
                    print(" -------/   ")
                    print(" |         |")
                    print(" |         |")
                    print(" | Vegas   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("       /----")
                    print(" -----/     ")
                    print(" |         |")
                    print(" |         |")
                    print(" | Vegas   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("     /------")
                    print(" ---/       ")
                    print(" |         |")
                    print(" |         |")
                    print(" | Vegas   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print("  /---------")
                    print(" /          ")
                    print(" |         |")
                    print(" |         |")
                    print(" | Vegas   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    sleep(0.5)
                    print(" -----------")
                    print("")
                    print(" |         |")
                    print(" |         |")
                    print(" | Vegas   |")
                    print(" |         |")
                    print(" |    pack |")
                    print(" |         |")
                    print(" |         |")
                    print(" -----------")
                    money -= 100
                    card1 = randint(1,75)
                    card2 = randint(1,75)
                    card3 = randint(1,75)
                    card4 = randint(1,75)
                    pack = [card1, card2, card3, card4,]
                    pack.sort()
                    for x in pack:
                        if x <= 74:
                            print ("You unpacked a...")
                            sleep(1)
                            print ("nothing! try again!")
                        if x <= 75 and x > 74:
                            inventory.append("mystery")
                            print ("You unpacked a...")
                            sleep(1)
                            print ("mystery!")

                    sleep(3)
            else:
                print("")
        if dostuff == "sell":
            print(inventory)
            sell = input("what would you like to sell? ")
            if sell == "all":
                for i in inventory:
                    if i == "common":
                        money += 1
                    if i == "uncommon":
                        money += 5
                    if i == "rare":
                        money += 10
                    if i == "unusual":
                        money += 15
                    if i == "epic":
                        money += 30
                    if i == "legendary":
                        money += 50
                    if i == "mythic":
                        money += 100
                    if i == "exotic":
                        money += 250
                    if i == "mystery":
                        money += 300
                inventory = []
            elif sell in inventory:    
                numsell = input("How many? ")
                x = 0
                numsell = int(numsell) #not subtracting cards and adding $$$$$
                while x < numsell:
                    if sell in inventory:
                        sellcard = inventory.index(sell)
                        if sell == "common":
                            inventory.remove ("common")
                            money += 1
                        if sell == "uncommon":
                            inventory.remove ("uncommon")
                            money += 5
                        if sell == "rare":
                            inventory.remove("rare")
                            money += 10
                        if sell == "unusual":
                            inventory.remove("unusual")
                            money += 15
                        if sell == "epic":
                            inventory.remove("epic")
                            money += 20
                        if sell == "legendary":
                            inventory.remove("legendary")
                            money += 30
                        if sell == "mythic":
                            inventory.remove("mythic")
                            money += 50
                        if sell == "exotic":
                            inventory.remove("exotic")
                            money += 100
                        if sell == "mystery":
                            inventory.remove("mystery")
                            money += 300
                        x += 1
            
            elif sell not in inventory :
                
                print("U don't hav dat card")
            print("you have...")
            sleep(0.5)
            print(money)
            sleep(0.5)
            print("money")
            
        else:
            print("")
#V0.5.3    
