from time import sleep
from random import randint
#(i) prefix 3 for text, 4 for bg, 9 for bright text, 10 for bright bg
#(i) \x1b[38;2;r;g;bm for rgb Text, \x1b[48;2;r;g;bm for rgb Background
#(i) \x1b[38;5;___m for 256 Text\x1b[48;5;___m for 256 Background, https://jakob-bagterp.github.io/colorist-for-python/ansi-escape-codes/extended-256-colors/#structure for all 256
#(v) the following are text
red = "\x1b[31m"
orange = "\x1b[38;5;208m" #(!) not working
yellow = "\x1b[33m"
green = "\x1b[32m"
blue = "\x1b[34m"
cyan = "\x1b[36m"
magenta = "\x1b[35m"
white = "\x1b[97m"
black = "\x1b[30m"
reset = "\x1b[0m"
#(v) the following are bgs
redbg = "\x1b[41m"
orangebg = "\x1b[48;5;208m" #(!) not working
yellowbg = "\x1b[43m"
greenbg = "\x1b[42m"
bluebg = "\x1b[44m"
cyanbg = "\x1b[46m"
magentabg = "\x1b[45m"
whitebg = "\x1b[107m"
blackbg = "\x1b[40m"
reset = "\x1b[0m"
print(red + "Welcome" + orange + " to" + yellow + " card" + green + " gaem" + blue + " 2" + reset)
print("nothing yet!")
money = 10
binder = []
def packanim(color):
    print(color)
    print(" ______________ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("                ")
    print(" _____________/ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("              /  ")
    print(" ____________/ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("              _")
    print("             /   ")
    print(" ___________/ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|") 
    sleep(0.1)
    print("             __")
    print("            /   ")
    print(" __________/ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("            ___")
    print("           /")
    print(" _________/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("           ____")
    print("          /")
    print(" ________/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("          _____")
    print("         /")
    print(" _______/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("         ______")
    print("        /")
    print(" ______/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("        _______")
    print("       /")
    print(" _____/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("       ________")
    print("      /")
    print(" ____/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|") 
    sleep(0.2)
    print("      _________")
    print("     /")
    print(" ___/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|") 
    sleep(0.1)
    print("     __________")
    print("    /")
    print(" __/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("    ___________")
    print("   /")
    print(" _/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|") 
    sleep(0.1)
    print("   ____________")
    print("  /")
    print(" /")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)    
    print("  _____________")
    print(" /")
    print(" ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1) 
    print(" ______________")
    print(" ")
    print(" ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")    
while True:
    menu = input("1. shop - 2. binder: ")
    if menu == "1":
        pack = input("what pack do you want to open? 1. base pack (10 money)")
        if pack == "1":
            if money >= 10:
                money -= 10
                #pack stuff
                print("opening pack...")
                card1 = randint(1,100)
                card2 = randint(1,100)
                cards = [card1, card2]
                colors = []
                for c in cards:
                    if c <= 75:
                        binder.append("common")
                        colors.append(blue)
                    elif c > 75 and c <= 100:
                        binder.append("uncommon")
                        colors.append(green)
                print(card1)
                packanim(reset)
                sleep(0.1)
                print(colors[1] + " ______________ ")
                print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
                print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
                print(reset + "|              |")
                print("|              |")
                print("|              |")
                print("|              |")
                print("|              |")
                print("|              |")
                print("|              |")
                print("|              |")
                print("|              |")
                print("|              |")
                print("|              |")
                print("|              |")
                print("|______________|")
                sleep(0.5)
                print("you got:")
                #(v) replace with something more efficient later
                for c in cards:
                    if c <= 75:
                        print(blue + "common")
                    elif c > 75 and c <= 100:
                        print(green + "uncommon")
            else:
                print("u really broke")
        else:
            print("typo, anyone?")
    elif menu == "2":
        print("no")
    else:
        print()
#vNA

