from time import sleep
from random import randint
#(i) prefix 3 for text, 4 for bg, 9 for bright text, 10 for bright bg
#(i) \x1b[38;2;r;g;bm for rgb Text, \x1b[48;2;r;g;bm for rgb Background
#(i) \x1b[38;5;___m for 256 Text\x1b[48;5;___m for 256 Background, https://jakob-bagterp.github.io/colorist-for-python/ansi-escape-codes/extended-256-colors/#structure for all 256
#(v) the following are text
red = "\x1b[31m"
yellow = "\x1b[33m"
green = "\x1b[32m"
blue = "\x1b[34m"
cyan = "\x1b[36m"
magenta = "\x1b[35m"
white = "\x1b[97m"
black = "\x1b[30m"
reset = "\x1b[0m"
#(v) the following are bgs
redbg = "\x1b[41m"
yellowbg = "\x1b[43m"
greenbg = "\x1b[42m"
bluebg = "\x1b[44m"
cyanbg = "\x1b[46m"
magentabg = "\x1b[45m"
whitebg = "\x1b[107m"
blackbg = "\x1b[40m"
reset = "\x1b[0m"
print(red + "Welcome" + magenta + " to" + yellow + " card" + green + " gaem" + blue + " 2" + reset)
print("nothing yet!")
money = 17
binder = []
def packanim(color):
    print(color)
    print(" ______________ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("                ")
    print(" _____________/ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("              /  ")
    print(" ____________/ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("              _")
    print("             /   ")
    print(" ___________/ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|") 
    sleep(0.1)
    print("             __")
    print("            /   ")
    print(" __________/ ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("            ___")
    print("           /")
    print(" _________/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("           ____")
    print("          /")
    print(" ________/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("          _____")
    print("         /")
    print(" _______/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("         ______")
    print("        /")
    print(" ______/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("        _______")
    print("       /")
    print(" _____/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("       ________")
    print("      /")
    print(" ____/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|") 
    sleep(0.2)
    print("      _________")
    print("     /")
    print(" ___/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|") 
    sleep(0.1)
    print("     __________")
    print("    /")
    print(" __/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)
    print("    ___________")
    print("   /")
    print(" _/")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|") 
    sleep(0.1)
    print("   ____________")
    print("  /")
    print(" /")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1)    
    print("  _____________")
    print(" /")
    print(" ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")
    sleep(0.1) 
    print(" ______________")
    print(" ")
    print(" ")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|              |")
    print("|______________|")    
while True:
    pack = input("what pack do you want to open? 1. base pack ("+yellow+"16"+reset+" money), 2. booster pack ("+yellow+"20"+reset+" money), 3. mega pack (" + yellow + "50" + reset + " money), 4. ultimate pack (" + yellow + "75" + reset + " money) you have " + yellow + str(money) + reset + " money: ")
    if pack == "1":
        #base pack
        if money >= 16:
            money -= 16
        #(v) pack stuff
            print("opening pack...")
            #(v) find cards
            card1 = randint(1,100)
            card2 = randint(1,100)
            card3 = randint(1,100)
            cards = [card1, card2, card3]
            cards.sort()
            colors = []
            for c in cards:
                #(v) common (75%)
                if c <= 75:
                    binder.append("common")
                    colors.append(blue)
                #(v) uncommon (25%)
                elif c > 75 and c <= 100:
                    binder.append("uncommon")
                    colors.append(green)
            #card animation
            packanim(reset)
            sleep(0.5)
            print(colors[0] + " ______________" )
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[1] + " ______________")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[2] + " ______________")
            print(colors[2] + "/" + colors[1] + "______________" + colors[2] + "\\")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(0.5)
            print("you got:")
            #(v) replace with something more efficient later
            for c in cards:
                if c <= 75:
                    print(blue + "common" + reset)
                elif c > 75 and c <= 100:
                    print(green + "uncommon" + reset)
        else:
            print("u really broke")
    #booster pack
    elif pack == "2":
        if money >= 20:
            money -= 20
            print("opening pack...")
            #(v) find cards
            card1 = randint(1,100)
            card2 = randint(1,100)
            cards = [card1, card2]
            cards.sort()
            colors = []
            for c in cards:
                #(v) common (35%)
                if c <= 35:
                    binder.append("common")
                    colors.append(blue)
                #(v) uncommon (30%)
                elif c > 35 and c <= 65:
                    binder.append("uncommon")
                    colors.append(green)
                #(v) rare (35%)
                elif c > 65 and c <= 100:
                    binder.append("epic")
                    colors.append(magenta)
            #card animation
            packanim(reset)
            sleep(0.5)
            print(colors[0] + " ______________" )
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[1] + " ______________ ")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(0.5)
            print("you got:")
            #(v) replace with something more efficient later
            for c in cards:
                if c <= 35:
                    print(blue + "common" + reset)
                elif c > 35 and c <= 65:
                    print(green + "uncommon" + reset)
                elif c > 65 and c <= 100:
                    print(magenta + "epic" + reset)
    #mega pack
    elif pack == "3":
        if money >= 50:
            money -= 50
            print("opening pack...")
            #(v) find cards
            card1 = randint(1,100)
            card2 = randint(1,100)
            card3 = randint(1,100)
            card4 = randint(1,100)
            card5 = randint(1,100)
            card6 = randint(1,100)
            cards = [card1, card2, card3, card4, card5, card6]
            cards.sort()
            colors = []
            for c in cards:
                #(v) common (30%)
                if c <= 30:
                    binder.append("common")
                    colors.append(blue)
                #(v) uncommon (10%)
                elif c > 30 and c <= 40:
                    binder.append("uncommon")
                    colors.append(green)
                #(v) rare (30%)
                elif c > 40 and c <= 70:
                    binder.append("rare")
                    colors.append(cyan)
                #(v) epic (20%)
                elif c > 70 and c <= 90:
                    binder.append("epic")
                    colors.append(magenta)  
                #(v) legendary (10%)
                elif c > 90 and c <= 100:
                    binder.append("legendary")
                    colors.append(yellow)
            #card animation
            packanim(reset)
            sleep(0.5)
            print(colors[0] + " ______________" )
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[1] + " ______________ ")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[2] + " ______________ ")
            print(colors[2] + "/" + colors[1] + "______________" + colors[2] + "\\")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[3] + " ______________ ")
            print(colors[3] + "/" + colors[2] + "______________" + colors[3] + "\\")
            print(colors[2] + "/" + colors[1] + "______________" + colors[2] + "\\")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[4] + " ______________ ")
            print(colors[4] + "/" + colors[3] + "______________" + colors[4] + "\\")
            print(colors[3] + "/" + colors[2] + "______________" + colors[3] + "\\")
            print(colors[2] + "/" + colors[1] + "______________" + colors[2] + "\\")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[5] + " ______________ ")
            print(colors[5] + "/" + colors[4] + "______________" + colors[5] + "\\")
            print(colors[4] + "/" + colors[3] + "______________" + colors[4] + "\\")
            print(colors[3] + "/" + colors[2] + "______________" + colors[3] + "\\")
            print(colors[2] + "/" + colors[1] + "______________" + colors[2] + "\\")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(0.5)
            print("you got:")
            #(v) replace with something more efficient later
            for c in cards:
                if c <= 30:
                    print(blue + "common" + reset)
                elif c > 30 and c <= 40:
                    print(green + "uncommon" + reset)
                elif c > 40 and c <= 70:
                    print(cyan + "rare" + reset)
                elif c > 70 and c <= 90:
                    print(magenta + "epic" + reset)  
                elif c > 90 and c <= 100:
                    print(yellow + "legendary" + reset)   
        else:
            print("u kinda broke")
    #ultimate pack  
    elif pack == "4":
        if money >= 75:
            money -= 75
            print("opening pack...")
            #(v) find cards
            card1 = randint(1,100)
            card2 = randint(1,100)
            card3 = randint(1,100)
            card4 = randint(1,100)
            card5 = randint(1,100)
            card6 = randint(1,100)
            cards = [card1, card2, card3, card4, card5, card6]
            cards.sort()
            colors = []
            for c in cards:
                #(v) common (15%)
                if c <= 15:
                    binder.append("common")
                    colors.append(blue)
                #(v) uncommon (10%)
                elif c > 15 and c <= 25:
                    binder.append("uncommon")
                    colors.append(green)
                #(v) rare (35%)
                elif c > 25 and c <= 60:
                    binder.append("rare")
                    colors.append(cyan)
                #(v) epic (20%)
                elif c > 60 and c <= 80:
                    binder.append("epic")
                    colors.append(magenta)  
                #(v) legendary (10%)
                elif c > 80 and c <= 90:
                    binder.append("legendary")
                    colors.append(yellow)
                #(v) mythic (10%)
                elif c > 90 and c <= 100:
                    binder.append("mythic")
                    colors.append(red)
            #card animation
            packanim(reset)
            sleep(0.5)
            print(colors[0] + " ______________" )
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[1] + " ______________ ")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[2] + " ______________ ")
            print(colors[2] + "/" + colors[1] + "______________" + colors[2] + "\\")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[3] + " ______________ ")
            print(colors[3] + "/" + colors[2] + "______________" + colors[3] + "\\")
            print(colors[2] + "/" + colors[1] + "______________" + colors[2] + "\\")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[4] + " ______________ ")
            print(colors[4] + "/" + colors[3] + "______________" + colors[4] + "\\")
            print(colors[3] + "/" + colors[2] + "______________" + colors[3] + "\\")
            print(colors[2] + "/" + colors[1] + "______________" + colors[2] + "\\")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(1)
            print(colors[5] + " ______________ ")
            print(colors[5] + "/" + colors[4] + "______________" + colors[5] + "\\")
            print(colors[4] + "/" + colors[3] + "______________" + colors[4] + "\\")
            print(colors[3] + "/" + colors[2] + "______________" + colors[3] + "\\")
            print(colors[2] + "/" + colors[1] + "______________" + colors[2] + "\\")
            print(colors[1] + "/" + colors[0] + "______________" + colors[1] + "\\")
            print(colors[0] + "/" + reset + "______________" + colors[0] + "\\")
            print(reset + "|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|              |")
            print("|______________|")
            sleep(0.5)
            print("you got:")
            #(v) replace with something more efficient later
            for c in cards:
                if c <= 15:
                    print(blue + "common" + reset)
                elif c > 15 and c <= 25:
                    print(green + "uncommon" + reset)
                elif c > 25 and c <= 60:
                    print(cyan + "rare" + reset)
                elif c > 60 and c <= 80:
                    print(magenta + "epic" + reset)  
                elif c > 80 and c <= 90:
                    print(yellow + "legendary" + reset)
                elif c > 90 and c <= 100:
                    print(red + "mythic" + reset)
        else:
            print("u kinda broke")

    elif pack != 1 and pack != 2 and pack != 3 and pack != 4:
        print("typo, anyone?")
    for c in binder:
        if c == "common":
            money += 5
        if c == "uncommon":
            money += 7
        if c == "rare":
            money += 12
        if c == "epic":
            money += 15
        if c == "legendary":
            money += 25
        if c == "mythic":
            money += 30
    binder = []
#v 1.1.0

